### PR TITLE
Add ability to attach a google meet link to calendar event

### PR DESCRIPTION
**Pull request by JoshTrebilco**
### This PR adds a new optional function to add a google meet link when creating an event.

When creating an Event, call `$event->addMeetLink();`

The meet link can then be accessed using the `$event->googleEvent->hangoutLink` property.

> This will add a Google Meet video conferencing link (similar to clicking this button on the event in Google Calendar):
> image

#### See screenshots below demonstrationing functionality.

> Code example with output:
> after
> The event can then be joined with google meet:
> with meet link

#### This feature is backwards compatible with existing implementations, and shouldn't have any breaking changes.

> Without Meet Link (existing functionality still works):
> without meet link

>Code example with output:
> before

Thanks for your time in reviewing this PR, I welcome any feedback or changes requested 😁

### CODE REVIEW

**Comment by freekmurze** [comment]
Thanks!

**Comment by MHSahebgharani** [comment]
This feature doesn't work for me
I keep getting this message from Google "Invalid conference type value" 

does this feature need google workspace account or anything else?

**Comment by JoshTrebilco** [comment]
> This feature doesn't work for me I keep getting this message from Google "Invalid conference type value"
> 
> does this feature need google workspace account or anything else?

I tested this using a Google Workspace account, with admin permissions for Google Calendar.

You might need to grant permission to attach conferenceData to the Calendar Event. Here's the section from the API that I referenced for this feature. [https://developers.google.com/calendar/api/v3/reference/events#methods:~:text=writable-,conferenceData,-nested%20object](https://developers.google.com/calendar/api/v3/reference/events#methods:~:text=writable-,conferenceData,-nested%20object)

Hope this helps! Let me know if you get this working and what you configured to fix it

**Comment by mohafiz** [comment]
> > This feature doesn't work for me I keep getting this message from Google "Invalid conference type value"
> > does this feature need google workspace account or anything else?
> 
> I tested this using a Google Workspace account, with admin permissions for Google Calendar.
> 
> You might need to grant permission to attach conferenceData to the Calendar Event. Here's the section from the API that I referenced for this feature. https://developers.google.com/calendar/api/v3/reference/events#methods:~:text=writable-,conferenceData,-nested%20object
> 
> Hope this helps! Let me know if you get this working and what you configured to fix it

Can you confirm that it doesn't need a Google Wrokspace account ?

**Comment by PrevailExcel** [comment]
> > > This feature doesn't work for me I keep getting this message from Google "Invalid conference type value"
> > > does this feature need google workspace account or anything else?
> > 
> > 
> > I tested this using a Google Workspace account, with admin permissions for Google Calendar.
> > You might need to grant permission to attach conferenceData to the Calendar Event. Here's the section from the API that I referenced for this feature. https://developers.google.com/calendar/api/v3/reference/events#methods:~:text=writable-,conferenceData,-nested%20object
> > Hope this helps! Let me know if you get this working and what you configured to fix it
> 
> Can you confirm that it doesn't need a Google Wrokspace account ?

Can anyone confirm this?

**Comment by matejvelikonja** [comment]
@JoshTrebilco is there a way to remove google meet link once it has been added? or you need to completely remove the event and re-add it?

**Comment by JoshTrebilco** [comment]
> @JoshTrebilco is there a way to remove google meet link once it has been added? or you need to completely remove the event and re-add it?

No, with the current implementation, it allows you to add but not remove the meet link for a given event. You're correct in thinking that the only way is to remove the event and re-add it.

**Pull request merged**
